# Generated by Django 5.1.2 on 2024-10-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_cart_items_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
